Closes #88: Add LCP Templates
wp-media/wp-rocket-e2e pull request #116
Opened 2024-06-19 01:44 UTC by Miraeld

# Description

Fixes #88 

## Documentation

### Technical documentation

This PR adds the following templates for Desktop AND Mobile: 

- lcp_bg_img_in_section
- lcp_section_template_relative
- lcp_section_template2
- lcp_picture_template
- lcp_bg_relative_attribute_incss
- lcp_bg_img_in_header_template
- lcp_6647_svgbg_template
- lcp_6599_template2
- lcp_picture_media_type_mixed
- lcp_picture_relative

## Type of change
- [x] Enhancement (non-breaking change which improves an existing functionality).

# Checklists

## Feature validation

- [x] I validated all the Acceptance Criteria. If possible, provide sreenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.

2024-06-19 09:52 UTC, jeawhanlee requested changes

2024-06-19 09:52 UTC, jeawhanlee commented on src/support/results/expectedResultsMobile.json
> +      "https://e2e.rocketlabsqa.ovh/wp-content/uploads/2024/03/should_be_lcp_atf_image.jpg"
```suggestion
      "/wp-content/uploads/2024/03/should_be_lcp_atf_image.jpg"
```

2024-06-19 09:52 UTC, jeawhanlee commented on src/support/results/expectedResultsDesktop.json
> +      "https://e2e.rocketlabsqa.ovh/wp-content/uploads/2024/03/should_be_lcp_atf_image.jpg"
```suggestion
      "/wp-content/uploads/2024/03/should_be_lcp_atf_image.jpg"
```

2024-06-19 14:09 UTC, Miraeld commented
Updated to comply latest feedback :)

2024-06-20 12:19 UTC, jeawhanlee submitted a review, later dismissed

2024-06-20 14:45 UTC, jeawhanlee commented
The viewport expectation for the template: `lcp_picture_template2` is wrong on mobile which causes a failure for that specific template. Manual testing shows this.

`Expected Viewport for mobile - /rocket-test-data/images/test3.gif for http://mike.e2e.rocketlabsqa.ovh/lcp_picture_template2 is not present in actual - [{"type":"picture","src":"http://mike.e2e.rocketlabsqa.ovh/wp-content/rocket-test-data/images/1_BDCYb3Yx8exGZVu5lLRPNw.png","sources":[{"srcset":"http://mike.e2e.rocketlabsqa.ovh/wp-content/rocket-test-data/images/lcp/testavif.avif","media":"","type":"","sizes":""}]},{"type":"picture","src":"http://mike.e2e.rocketlabsqa.ovh/test.png","sources":[]},{"type":"picture","src":"http://mike.e2e.rocketlabsqa.ovh/wp-content/rocket-test-data/images/lcp/testwebp.webp","sources":[{"srcset":"http://mike.e2e.rocketlabsqa.ovh/wp-content/rocket-test-data/images/paper.jpeg","media":"(max-width: 400px)","type":"","sizes":""},{"srcset":"http://mike.e2e.rocketlabsqa.ovh/wp-content/rocket-test-data/images/lcp/testjpeg.jpeg","media":"(max-width: 800px)","type":"","sizes":""}]}]`


`Expected Viewport for mobile - /rocket-test-data/images/testjpg3.jpg for http://mike.e2e.rocketlabsqa.ovh/lcp_picture_template2 is not present in actual - [{"type":"picture","src":"http://mike.e2e.rocketlabsqa.ovh/wp-content/rocket-test-data/images/1_BDCYb3Yx8exGZVu5lLRPNw.png","sources":[{"srcset":"http://mike.e2e.rocketlabsqa.ovh/wp-content/rocket-test-data/images/lcp/testavif.avif","media":"","type":"","sizes":""}]},{"type":"picture","src":"http://mike.e2e.rocketlabsqa.ovh/test.png","sources":[]},{"type":"picture","src":"http://mike.e2e.rocketlabsqa.ovh/wp-content/rocket-test-data/images/lcp/testwebp.webp","sources":[{"srcset":"http://mike.e2e.rocketlabsqa.ovh/wp-content/rocket-test-data/images/paper.jpeg","media":"(max-width: 400px)","type":"","sizes":""},{"srcset":"http://mike.e2e.rocketlabsqa.ovh/wp-content/rocket-test-data/images/lcp/testjpeg.jpeg","media":"(max-width: 800px)","type":"","sizes":""}]}]`


`Expected Viewport for mobile - /rocket-test-data/images/lcp/testjpg2.jpg for http://mike.e2e.rocketlabsqa.ovh/lcp_picture_template2 is not present in actual - [{"type":"picture","src":"http://mike.e2e.rocketlabsqa.ovh/wp-content/rocket-test-data/images/1_BDCYb3Yx8exGZVu5lLRPNw.png","sources":[{"srcset":"http://mike.e2e.rocketlabsqa.ovh/wp-content/rocket-test-data/images/lcp/testavif.avif","media":"","type":"","sizes":""}]},{"type":"picture","src":"http://mike.e2e.rocketlabsqa.ovh/test.png","sources":[]},{"type":"picture","src":"http://mike.e2e.rocketlabsqa.ovh/wp-content/rocket-test-data/images/lcp/testwebp.webp","sources":[{"srcset":"http://mike.e2e.rocketlabsqa.ovh/wp-content/rocket-test-data/images/paper.jpeg","media":"(max-width: 400px)","type":"","sizes":""},{"srcset":"http://mike.e2e.rocketlabsqa.ovh/wp-content/rocket-test-data/images/lcp/testjpeg.jpeg","media":"(max-width: 800px)","type":"","sizes":""}]}]`

2024-06-20 15:34 UTC, jeawhanlee approved these changes

2024-06-20 16:25 UTC, MathieuLamiot commented
All good here on the new templates.

2024-06-20 16:25 UTC, merged