added function for changing permalink. created performance-hints file…
wp-media/wp-rocket-e2e pull request #136
Opened 2024-08-23 07:47 UTC by hanna-meda

Added function for changing permalink. created performance-hints files and added steps for 2 scenarios

# Description

Partial work on #126 

- added function for changing permalink under utils > page-utils.ts
- created performance-hints.ts & performance-hints.feature files

This commit covers:
Scenario: Should clear performance hints data when click clear PH in admin bar 
Given WPR installed and activated 
And performance hints data added to DB 
When clear performance hints is clicked in admin bar 
Then data is removed from the performance hints tables

Scenario: Should clear performance hints when change permalinks 
Given WPR installed and activated 
And performance hints data added to DB 
When permalinks is changed 
Then data is removed from the performance hints tables

Note: Scenarios still need more testing and refinement.

2024-08-23 13:18 UTC, jeawhanlee commented on src/support/steps/performance-hints.ts
> +import assert from "assert";
Why did you not use expect that's built directly into PW?

2024-08-23 13:18 UTC, jeawhanlee commented
@hanna-meda Overall Good Job 🙌

2024-08-26 07:55 UTC, hanna-meda commented on src/support/steps/performance-hints.ts
> +import assert from "assert";
You are right. I used 'assert', and then mid-way I saw we had 'expect' for that. Forgot to change it here as well. Corrected in `4868e94f141875ce9e72fc2721dbb5d3b4bc61e4`. Thank you!

2024-09-02 13:31 UTC, jeawhanlee requested changes

2024-09-02 13:31 UTC, jeawhanlee commented on package.json
> +    "test:hints": "$npm_package_config_testCommand --tags @hints",
Should the tag not be `@performancehints`?

2024-09-02 13:31 UTC, jeawhanlee commented on src/features/performance-hints.feature
> +        And performance hints data added to DB
Personally I don't like starting a scenario with the `And`, `But` or `Then`. For this case it looks like a precondition, so it would be better if you started with a `Given`

2024-09-02 13:31 UTC, jeawhanlee commented on src/features/performance-hints.feature
> +    @hints
Why do we have the tag for only this scenario, should we not make this global to this test feature?

2024-09-02 13:31 UTC, jeawhanlee commented on src/features/performance-hints.feature
> +        And performance hints data added to DB
We should start with a precondition like `Given` here also

2024-09-10 11:48 UTC, jeawhanlee requested changes

2024-09-10 11:48 UTC, jeawhanlee commented on src/support/steps/general.ts
> +When('I go to {string} desktop accepted size', async function (this: ICustomWorld, page) {
We already have a step definition for this kind of step: https://github.com/wp-media/wp-rocket-e2e/blob/ffbb4e744536df78d9ca717f7942f3e3851c2052/src/support/steps/general.ts#L255

2024-09-10 11:48 UTC, jeawhanlee commented on src/support/steps/performance-hints.ts
> +When ('I edit the content of the {string}', async function (this: ICustomWorld, permalink: string) {
There's an argument of permalink parsed but not used in the body.

2024-09-13 13:03 UTC, Mai-Saad commented on src/support/steps/performance-hints.ts
> +    const tablePrefix = await getWPTablePrefix();
@hanna-meda @jeawhanlee what do you think about having utility to seed data in DB and be called here?

2024-09-13 14:36 UTC, jeawhanlee commented on src/support/steps/performance-hints.ts
> +    const tablePrefix = await getWPTablePrefix();
I think that makes sense, we can do that.

2024-09-20 11:44 UTC, Mai-Saad commented
test results
[cucumber-report.json](https://github.com/user-attachments/files/17074600/cucumber-report.json)

2024-09-23 10:26 UTC, Miraeld approved these changes

2024-09-23 10:34 UTC, jeawhanlee approved these changes

2024-09-23 10:38 UTC, Mai-Saad approved these changes

2024-09-23 10:38 UTC, Mai-Saad commented on src/support/steps/performance-hints.ts
> +    await this.page.waitForLoadState('load', { timeout: 30000 });
If we removed wait here can see that test is green, do you think we can remove it?

2024-09-24 08:57 UTC, merged