WIP: LL Not applied to LCP
wp-media/wp-rocket-e2e pull request #144
Opened 2024-09-18 03:11 UTC by Miraeld

# Description

Fixes #(issue number)
*Explain how this code impacts users.*

## Type of change

- [ ] New feature (non-breaking change which adds functionality).
- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] Enhancement (non-breaking change which improves an existing functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as before).
- [ ] Sub-task of #(issue number)
- [ ] Release

## Detailed scenario

*Explain how to reproduce the issue (for bugs) or how to trigger the new code. You can refer to the GitHub issue or grooming if it is still applicable.*

## Technical description

### Documentation

*Explain how this code works. Diagrams & drawings are welcome.*

### New dependencies

*List any new dependencies that are required for this change.*

### Risks

*List possible performance & security issues or risks, and explain how they have been mitigated.*

# Mandatory Checklist

## Code validation

- [ ] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [ ] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I implemented built-in tests to cover the new/changed code.

## Code style
- [ ] I wrote a self-explanatory code about what it does.
- [ ] I protected entry points against unexpected inputs.
- [ ] I did not introduce unnecessary complexity.
- [ ] Output messages (errors, notices, logs) are explicit enough for users to understand the issue and are actionnable.

# Additional Checks
- [ ] In the case of complex code, I wrote comments to explain it.
- [ ] When possible, I prepared ways to observe the implemented system (logs, data, etc.).
- [ ] I added error handling logic when using functions that could throw errors (HTTP/API request, filesystem, etc.)

2024-09-24 12:27 UTC, jeawhanlee requested changes

2024-09-24 12:27 UTC, jeawhanlee commented on src/features/ll-lcp.feature
> +    And delete 'wp-rocket' plugin
Why are we deleting wp-rocket here? we already do that with the setup tag

2024-09-24 12:27 UTC, jeawhanlee commented on src/support/steps/general.ts
> +    deactivatePlugin, deletePlugin, installRemotePlugin,
```suggestion
    deactivatePlugin, uninstallPlugin, installRemotePlugin,
```

2024-09-24 12:27 UTC, jeawhanlee commented on src/support/steps/general.ts
> +    await deletePlugin(plugin)
```suggestion
    await uninstallPlugin(plugin)
```

2024-09-24 12:27 UTC, jeawhanlee commented on src/support/steps/imagify.ts
> +});
While I can see that the selector query here is simple, we should as much as possible avoid parsing the selector to the click method as it's not as flexible as the locator for performing more complex query. but this is fine.

Also after we make a click action or perform an action that reloads the page, we should always assert that the action just performed was as expected by checking that expected elements are now visible on the DOM since we now discourage the use `waitForLoadState` anymore. This will help reduce flaky tests.

2024-09-24 12:27 UTC, jeawhanlee commented on utils/commands.ts
> +    return await wp(`plugin delete ${name}`, false);
This will only remove plugin file but not the data such as DB tables and cache folder among other things as it does not respect the uninstall.php or uninstall hook. we already have a command for uninstalling plugins completely here: https://github.com/wp-media/wp-rocket-e2e/blob/221c9d21605df18c9a96cb65509f71480f01cefa/utils/commands.ts#L274

2024-09-26 10:04 UTC, Khadreal commented on src/features/ll-lcp.feature
> +    And delete 'wp-rocket' plugin
this line will always fail `And plugin is installed 'new_release'` if there's a wp-rocket installed on the test site

2024-09-26 10:08 UTC, Khadreal commented on src/features/ll-lcp.feature
> +    And delete 'wp-rocket' plugin
Update:
This was because `@setup` wasn't added during that test.

2024-09-26 10:18 UTC, Khadreal commented on src/support/steps/general.ts
> +    await deletePlugin(plugin)
This is for deleting the plugin, I think we should leave at that.

2024-09-26 10:21 UTC, Khadreal commented on utils/commands.ts
> +    return await wp(`plugin delete ${name}`, false);
Updated the function description to note this

2024-10-02 12:18 UTC, jeawhanlee submitted a review, later dismissed

2024-10-03 13:10 UTC, hanna-meda commented
@Khadreal @jeawhanlee  cc @Miraeld, for me `@lcpll` tests on PR #144 still fail, with error in debug.log
```
PHP Fatal error:  Uncaught Error: Call to undefined function undefined() in /var/www/html/hanna.e2e.rocketlabsqa.ovh/wp-content/rocket-test-data/templates/triggerErrorInDebug.php:6
Stack trace:
#0 /var/www/html/hanna.e2e.rocketlabsqa.ovh/wp-includes/template-loader.php(106): include()
#1 /var/www/html/hanna.e2e.rocketlabsqa.ovh/wp-blog-header.php(19): require_once('...')
#2 /var/www/html/hanna.e2e.rocketlabsqa.ovh/index.php(17): require('...')
#3 {main}
  thrown in /var/www/html/hanna.e2e.rocketlabsqa.ovh/wp-content/rocket-test-data/templates/triggerErrorInDebug.php on line 6
```
And the e2e rocket helper plugin I think needs to be updated with new hook name:
`PHP Deprecated:  Hook rocket_lcp_delay is deprecated since version 3.16.4! Use rocket_performance_hints_optimization_delay instead. in /var/www/html/hanna.e2e.rocketlabsqa.ovh/wp-includes/functions.php on line 6078`
and even though scenarios with Imagify are expected to fail due to Imagify issue, the 1 scenario at least should be expected to pass, but it fails. Sharing my results below, if one of you can help me debug. Thanks.

[tests_results_lcpll_on_PR144.txt](https://github.com/user-attachments/files/17244604/tests_results_lcpll_on_PR144.txt)
[cucumber-report-html-2024-10-03-16_08_23.pdf](https://github.com/user-attachments/files/17244640/cucumber-report-html-2024-10-03-16_08_23.pdf)
video: [da516a9a1894b1fa7cca3489cd808cb0.webm](https://github.com/user-attachments/assets/9adccd1f-d08d-4c0b-9fff-ba83ddf3c693)

2025-01-06 14:27 UTC, Khadreal commented
@hanna-meda please could you try to run this test again and let me know if you're still getting an error

2025-01-06 19:16 UTC, hanna-meda commented
@Khadreal This time I didn't encounter any errors, but test results are still the same, 3 out of 3 tests failing for `@lcpll`. 
You can review the results [here](https://jmp.sh/5e7tghRs).

I’ll investigate this further when I’m back at work on Thursday. In the meantime, @Mai-Saad, if you'll be able to take a look on your end before then, it would be greatly appreciated.

2025-01-08 08:10 UTC, wordpressfan submitted a review, later dismissed

2025-01-09 12:02 UTC, Mai-Saad commented on package.json
> +    "test:lcpll": "$npm_package_config_testCommand --tags @lcpll",
Why don't we use the current lcp tag?

2025-01-09 12:02 UTC, Mai-Saad commented on src/features/ll-lcp.feature
> +    And I save settings 'media' 'lazyloadCssBgImg'
now only llbg is enabled, in the main ticket, we need to enable rest of LL options. what do you think @Khadreal ?

2025-01-09 12:02 UTC, Mai-Saad commented on package.json
> +    "test:lcpll": "$npm_package_config_testCommand --tags @lcpll",
if we added new tag so that the original one , run with default config while here with LL .. Do you think we need new cmd to run both tests?

2025-01-09 12:07 UTC, Khadreal commented on package.json
> +    "test:lcpll": "$npm_package_config_testCommand --tags @lcpll",
Yes, we should have one tag for both. since they're related. This was already done before I took over the PR.
I'll make some adjustments to reflect this.

2025-01-09 12:07 UTC, Khadreal commented on src/features/ll-lcp.feature
> +    And I save settings 'media' 'lazyloadCssBgImg'
Noted, nice catch. I'll update the steps for this

2025-01-10 10:37 UTC, Mai-Saad commented on src/features/ll-lcp.feature
> +    And I clear cache
Do we need this step? knowing that changing settings in the background step will clear the cache

2025-01-10 15:28 UTC, Mai-Saad approved these changes
last run all green (note: sometimes the test to check fetch priority in the page fails, if it happened on dev we can open separate GH for further investigation)
![Screenshot from 2025-01-10 17-25-26](https://github.com/user-attachments/assets/ad05f60a-d881-440e-a8ad-371c4cf23357)

2025-01-10 15:28 UTC, merged