Closes #137 LRC visual regression on live templates
wp-media/wp-rocket-e2e pull request #145
Opened 2024-09-18 12:15 UTC by Khadreal

# Description

Fixes #137 

## Type of change

- [x] New feature (non-breaking change which adds functionality).

## Detailed scenario
Allow QA to test for any visual regression on LRC templates

## Technical description

### Documentation
Allow QA to test for any visual regression on LRC templates

### New dependencies
N/A

### Risks
N/A

# Mandatory Checklist

## Code validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I implemented built-in tests to cover the new/changed code.

## Code style
- [x] I wrote a self-explanatory code about what it does.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unnecessary complexity.
- [x] Output messages (errors, notices, logs) are explicit enough for users to understand the issue and are actionnable.

2024-09-24 02:48 UTC, Miraeld submitted a review, later dismissed

2024-09-24 07:21 UTC, jeawhanlee requested changes

2024-09-24 07:21 UTC, jeawhanlee commented on src/features/lrc-visual-regression.feature
> +      And I visit lrc live templates
Can we make this test generic, some more like `And I visit scenario urls`

2024-09-24 07:21 UTC, jeawhanlee commented on src/support/steps/general.ts
> +    await this.page.locator("text=Clear and preload").last().click();
Does this work as expected even when preload is disabled?

2024-09-24 07:21 UTC, jeawhanlee commented on src/support/steps/general.ts
> +        await compareReference(liveUrl[key]);
Should this not be the key instead?

2024-09-24 07:39 UTC, jeawhanlee commented
Currently backstop tests are not running well, because of my comment [here](https://github.com/wp-media/wp-rocket-e2e/pull/145#discussion_r1772770188)

2024-09-24 08:28 UTC, Khadreal commented on src/support/steps/general.ts
> +    await this.page.locator("text=Clear and preload").last().click();
Didn't test with preload disabled, will check

2024-09-24 08:40 UTC, jeawhanlee commented on src/support/steps/general.ts
> +    await this.page.locator("text=Clear and preload").last().click();
You can use the `pre_get_rocket_option_manual_preload` filter

2024-09-24 13:10 UTC, jeawhanlee commented on src/support/steps/general.ts
> +    await this.page.locator("text=Clear and preload").last().click();
I can confirm this is fixed now.

2024-09-24 13:10 UTC, jeawhanlee submitted a review, later dismissed

2024-09-26 10:05 UTC, jeawhanlee submitted a review, later dismissed

2024-10-01 12:11 UTC, Mai-Saad commented on config/scenarioUrls.json
> +      "path": "lcp_live_test_span"
Let's remove this template from e2e as it's failing cause of edge acceptable case https://wp-media.slack.com/archives/CUKB44GNN/p1727454310142779?thread_ts=1727444219.707339&cid=CUKB44GNN

2024-10-04 11:05 UTC, Mai-Saad commented
@Khadreal Thanks for the PR 
- test itself is passing
- backstop for VR  (4passes/8) => Note for lcp_live_4 , removed recaptcha js so that it works {pushed to test repo}
- Now failed templates that may need update or removal:
delayjs_1-3_live_template
lcp_live_test_span
rucss_5213_template
lrcWillSite

2024-10-10 08:27 UTC, Mai-Saad commented
- If WPR was installed before running the test, it won't be removed when running the tests causing failure at install step (further investigations needed)

2024-10-11 13:08 UTC, Khadreal commented
I did another round of test and the plugin was removed when the test was running. @jeawhanlee could help run the test when you have some time.

2024-10-11 17:32 UTC, jeawhanlee commented
I can confirm with @Khadreal that the plugin will be removed from the env if it was already installed before running tests.

2024-10-17 12:38 UTC, Mai-Saad commented
open another ticket for the uninstall issue https://github.com/wp-media/wp-rocket-e2e/issues/153

2024-10-17 12:39 UTC, Mai-Saad approved these changes
Handle failed templated can be on other PR https://github.com/wp-media/wp-rocket-e2e/issues/154

2024-10-17 14:46 UTC, merged