Fix #163 Modify delete plugin method, remove auth from method -- :close #163
wp-media/wp-rocket-e2e pull request #164
Opened 2024-10-24 10:12 UTC by Khadreal

# Description

Fixes #163 
Modify the delete plugin feature.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue).

## Detailed scenario

Use the `deleteWPRViaUI` option when deleting the plugin

## Technical description

### Documentation

# Mandatory Checklist

## Code validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I implemented built-in tests to cover the new/changed code.

## Code style
- [x] I wrote a self-explanatory code about what it does.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unnecessary complexity.

2024-10-24 12:52 UTC, Miraeld approved these changes, later dismissed

2024-10-25 12:08 UTC, jeawhanlee requested changes

2024-10-25 12:08 UTC, jeawhanlee commented on utils/page-utils.ts
> -        await this.auth();
Removing this line will bring a regression for local testing. Instead we should move both actions ( `await this.visitPage('wp-admin')`, `await this.auth()` ) into this condition: https://github.com/wp-media/wp-rocket-e2e/blob/221c9d21605df18c9a96cb65509f71480f01cefa/utils/page-utils.ts#L584
That way we can completely isolate the method's functionality.

2024-10-28 10:30 UTC, jeawhanlee approved these changes

2024-10-29 17:57 UTC, hanna-meda approved these changes
Thank you, @Khadreal, for this PR.
Running smoke on e2e on PR #164 with 3.17.2-alpha1 all tests pass.
[cucumber-report-PR164.html.zip](https://github.com/user-attachments/files/17561142/cucumber-report-PR164.html.zip)

2024-10-30 05:23 UTC, merged