Closes #143 Add report add process to rename and push test files to git
wp-media/wp-rocket-e2e pull request #174
Opened 2024-11-21 10:25 UTC by Khadreal

# Description

Fixes #143 
Organise report after running a test

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality).

## Detailed scenario

*Explain how to reproduce the issue (for bugs) or how to trigger the new code. You can refer to the GitHub issue or grooming if it is still applicable.*

## Technical description

### Documentation

*Explain how this code works. Diagrams & drawings are welcome.*

### New dependencies

*List any new dependencies that are required for this change.*

### Risks

*List possible performance & security issues or risks, and explain how they have been mitigated.*

# Mandatory Checklist

## Code validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I implemented built-in tests to cover the new/changed code.

## Code style
- [x] I wrote a self-explanatory code about what it does.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unnecessary complexity.
- [x] Output messages (errors, notices, logs) are explicit enough for users to understand the issue and are actionnable.

2025-01-03 08:06 UTC, wordpressfan requested changes
Thanks @Khadreal 
do we really need shell file for that task? I was thinking of making the whole code in JS, this will increase simplicity and maintainability.

https://nodejs.org/docs/latest/api/fs.html#fs_fs_rename_oldpath_newpath_callback

What do u think?

2025-01-03 13:48 UTC, jeawhanlee commented
@MathieuLamiot I have a question from the A/C [here](https://github.com/wp-media/wp-rocket-e2e/issues/143#issue-2531575441)
Does the 2nd point need to be catered for in this PR? or this would be deleted by the QA after it's stored, because I see that this PR would store reports for every run.

> We don't need to store all the reports from all the runs we do, but we would need to keep the representative ones (typically when a next version of the plugin and/or the rocket-E2E is released or tagged)?

2025-01-03 14:13 UTC, Khadreal commented
No @jeawhanlee, it doesn't store report for every run. It only move the reports and store when the `tag` parameter is set.

2025-01-03 14:34 UTC, jeawhanlee commented
@Khadreal Correct if I'm wrong, we will move reports & store every time for general test run as well as smoke? no?

2025-01-03 14:50 UTC, Khadreal commented
@jeawhanlee we would only move report and store for general and smoke test if tag parameter are present if not we wouldn't and the behaviour remains the same before now.

2025-01-03 15:08 UTC, jeawhanlee commented
I had a discussion with @Khadreal, Thanks for the clarification

2025-01-03 15:24 UTC, jeawhanlee submitted a review, later dismissed

2025-01-08 13:37 UTC, Mai-Saad commented
@Khadreal Thanks for the PR, for me the report is not added in /var/shared/rocket-e2e-reports folder and no error in the terminal.

2025-01-08 23:28 UTC, Khadreal commented
> @Khadreal Thanks for the PR, for me the report is not added in /var/shared/rocket-e2e-reports folder and no error in the terminal.

I tried running this in your env and found the issue, the smoke test was failing, I've made a slight modifications to it even if the test fail it should still move/store the report.

2025-01-09 12:18 UTC, Mai-Saad commented
Thanks, @Khadreal , I can see the report is generated on the shared folder now
![Screenshot from 2025-01-09 14-12-31](https://github.com/user-attachments/assets/fc74641b-1ba0-4835-903e-29ac0a9321a0)

2025-01-09 13:02 UTC, jeawhanlee approved these changes

2025-01-10 12:19 UTC, wordpressfan approved these changes

2025-01-10 13:16 UTC, merged

2025-01-10 16:53 UTC, hanna-meda commented
Thank you, @Khadreal. 
Confirming that I, too, can see my report is generated and added to the shared folder:
<img width="659" alt="Screenshot 2025-01-10 at 18 53 06" src="https://github.com/user-attachments/assets/acde6437-3188-4bcd-a92d-202fbe0d2224" />