Add step one test for wpml
wp-media/wp-rocket-e2e pull request #46
Opened 2024-02-08 09:16 UTC by Khadreal

## Description

Not completed yet, this only capture the first scenarios for wpml test

Fixes #23 

## Type of change
- New feature (non-breaking change which adds functionality).

## Is the solution different from the one proposed during the grooming?

*Please describe in this section if there is any change to the groomed solution, and why.*

# Checklists

## Generic development checklist

- [ ] My code follows the style guidelines of this project, with adapted comments and without new warnings.
- [ ] I have added unit and integration tests that prove my fix is effective or that my feature works.
- [ ] The CI passes locally with my changes (including unit tests, integration tests, linter).
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] If applicable, I have made corresponding changes to the documentation. *Provide a link to the documentation.*

## Test summary

- [ ] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I validated all Acceptance Criteria of the related issues. (If applicable, provide proof).
- [ ] I validated all test plan the QA Review asked me to.

*If not, detail what you could not test.*

*Please describe any additional tests you performed.*

2024-02-09 14:19 UTC, jeawhanlee requested changes

2024-02-09 14:19 UTC, jeawhanlee commented on src/features/wpml-compatibility.feature
> +      Given wpml directory is enabled
We can move this to the background as it doesn't perform any tests on wp-rocket but rather set preconditions.

2024-02-09 14:19 UTC, jeawhanlee commented on utils/page-utils.ts
> +
This is a nice to have helper method, that's why we already have one which you can use - https://github.com/wp-media/wp-rocket-e2e/blob/29552126306e6552e435e14e762d507dcd6424b8/utils/page-utils.ts#L95
```suggestion
```

2024-02-09 14:19 UTC, jeawhanlee commented on src/support/steps/wpml.ts
> +Then('switch to another language', async function () {
This step definition is ambiguous. Is it supposed to handle check for console errors or just switch theme?

2024-02-09 14:19 UTC, jeawhanlee commented on src/support/steps/wpml.ts
> +    const checkboxes = await this.page.$$('.available-languages li input[type=checkbox]');
This is discouraged by playwright, you can try using this.page.locator('.available-languages li input[type=checkbox]')

2024-02-09 14:19 UTC, jeawhanlee commented on src/support/steps/wpml.ts
> +    await this.utils.gotoPage('/wp-admin/admin.php?page=sitepress-multilingual-cms%2Fmenu%2Flanguages.php');
```suggestion
    await this.utils.visitPage('wp-admin/admin.php?page=sitepress-multilingual-cms%2Fmenu%2Flanguages.php');
```

2024-02-09 14:19 UTC, jeawhanlee commented on src/support/steps/wpml.ts
> +Given('wpml has more than one languages', async function () {
```suggestion
Given('wpml has more than one languages', async function (this:ICustomWorld) {
```

2024-02-09 14:19 UTC, jeawhanlee commented on src/support/steps/wpml.ts
> +Given('I save wpml language settings', async function () {
```suggestion
Given('I save wpml language settings', async function (this:ICustomWorld) {
```

2024-02-09 14:19 UTC, jeawhanlee commented on src/support/steps/wpml.ts
> +    await this.page.pause()
```suggestion
```

2024-02-09 14:19 UTC, jeawhanlee commented on src/support/steps/wpml.ts
> +    await this.utils.gotoPage('/wp-admin/admin.php?page=sitepress-multilingual-cms%2Fmenu%2Flanguages.php');
```suggestion
    await this.utils.visitPage('wp-admin/admin.php?page=sitepress-multilingual-cms%2Fmenu%2Flanguages.php');
```

2024-02-09 14:19 UTC, jeawhanlee commented on src/support/steps/wpml.ts
> +Given('wpml query string is enabled', async function () {
```suggestion
Given('wpml query string is enabled', async function (this:ICustomWorld) {
```

2024-02-09 14:19 UTC, jeawhanlee commented on src/support/steps/wpml.ts
> +Given('wpml directory is enabled', async function() {
```suggestion
Given('wpml directory is enabled', async function(this:ICustomWorld) {
```

2024-02-09 14:19 UTC, jeawhanlee commented on src/support/steps/wpml.ts
> +
You need to import the interface:
import { ICustomWorld } from "../../common/custom-world";

2024-02-09 14:19 UTC, jeawhanlee commented on src/support/steps/general.ts
> +Given('activate {string} plugin', async function (plugin) {
```suggestion
Given('activate {string} plugin', async function (this:ICustomWorld, plugin) {
```

2024-02-09 14:19 UTC, jeawhanlee commented on src/support/steps/general.ts
> +    await this.utils.togglePluginActivation(plugin, true);
2nd param will evaluate to true by default, no need to declare.
```suggestion
    await this.utils.togglePluginActivation(plugin);
```

2024-02-09 14:19 UTC, jeawhanlee commented on src/features/wpml-compatibility.feature
> +      Then switch to another language
Same here
```suggestion
      When switch to another language
```

2024-02-09 14:19 UTC, jeawhanlee commented on src/features/wpml-compatibility.feature
> +      Then switch to another language
We typically use Then step to describe an expected outcome. in this context you are describing and event or action, we should use `When`
```suggestion
      When switch to another language
```

2024-02-09 16:19 UTC, Khadreal commented on src/support/steps/wpml.ts
> +Then('switch to another language', async function () {
It's responsible for switching to new language and checking for console error, maybe rename the step

2024-02-09 16:24 UTC, jeawhanlee commented on src/support/steps/wpml.ts
> +Then('switch to another language', async function () {
ok if so, we can simply just use the already defined step for this: `Then no error in the console different than nowprocket page 'ar'`
In this context I passed arabic so it will pretty much switch to that language and do the console check

2024-02-12 14:27 UTC, Khadreal commented on src/support/steps/wpml.ts
> +Then('switch to another language', async function () {
Will it switch to https://e2e.rocketlabsqa.ovh/lazyload_css_background_images/ in arabic or just the homepage ?

2024-02-13 09:48 UTC, jeawhanlee requested changes

2024-02-13 09:48 UTC, jeawhanlee commented on backstop.json
We should leave the scenarios property as an empty array and add this file to .gitignore

2024-02-13 09:48 UTC, jeawhanlee commented on src/features/wpml-compatibility.feature
> +      Given wpml directory is enabled
We can use `And` to join preconditions or actions 
```suggestion
      And wpml has more than one languages
      And wpml directory is enabled
```

2024-02-13 09:48 UTC, jeawhanlee commented on src/support/steps/wpml.ts
> +When('switch to another language', async function () {
```suggestion
When('switch to another language', async function (this:ICustomWorld) {
```

2024-02-13 09:53 UTC, Khadreal commented on backstop.json
Okay.

2024-02-13 10:01 UTC, jeawhanlee requested changes

2024-02-13 10:01 UTC, jeawhanlee commented on backstop.json
> +  ],
```suggestion
  "scenarios": [],
```

2024-02-13 10:34 UTC, jeawhanlee submitted a review, later dismissed

2024-02-13 14:48 UTC, MathieuLamiot commented
Need #45 merged first

2024-02-16 12:33 UTC, jeawhanlee commented
@Khadreal Could you merge trunk into this PR branch to keep it updated.

2024-04-03 16:56 UTC, hanna-meda approved these changes
Everything seems to be in order. Both scenarios have passed on my end. The steps accurately perform or verify what's required. I have also validated that the steps correspond with those in TestRail.

2024-04-03 16:56 UTC, merged