Closes #55: Adds template to e2e tests
wp-media/wp-rocket-e2e pull request #58
Opened 2024-03-26 09:25 UTC by Miraeld

# Description

Fixes #55 

## Documentation

### User documentation

### Technical documentation

Pages https://e2e.rocketlabsqa.ovh/ll_bg_css_double_colon/ & https://e2e.rocketlabsqa.ovh/ll_bg_css_single_colon/ have been created to ensure the test are running.

## Type of change
- [x] Enhancement (non-breaking change which improves an existing functionality).

2024-03-26 15:49 UTC, jeawhanlee requested changes

2024-03-26 15:49 UTC, jeawhanlee commented on src/features/ll-css-bg-image-simple-colon.feature
> +Feature: C14626 - Should lazyload CSS background images inside internal, and external CSS - Simple colon
```suggestion
Feature: C14626 - Should lazyload CSS background images inside internal, and external CSS - Single colon
```

2024-03-26 15:49 UTC, jeawhanlee commented on src/features/ll-css-bg-image-simple-colon.feature
We should change this file as well to `ll-css-bg-image-single-colon.feature`

2024-03-27 08:43 UTC, jeawhanlee approved these changes

2024-03-27 10:35 UTC, jeawhanlee requested changes

2024-03-27 10:35 UTC, jeawhanlee commented on config/wp.config.sample.ts
> +		path: 'll_bg_css_simple_colon'
```suggestion
		path: 'll_bg_css_single_colon'
```

2024-03-27 11:32 UTC, jeawhanlee requested changes

2024-03-27 11:32 UTC, jeawhanlee commented on config/wp.config.sample.ts
> +	llcssDoubleColon: {
```suggestion
	DoubleColonLlcss: {
```

2024-03-27 11:32 UTC, jeawhanlee commented on config/wp.config.sample.ts
> +	llcssSingleColon: {
```suggestion
	SingleColonLlcss: {
```

2024-03-27 11:32 UTC, jeawhanlee commented on config/wp.config.sample.ts
> +	llcssDoubleColon: {
Reason for this is because backstop when testing `llcss` will use regex to match all label scenario starting with `llcss` and will run all of them and we don't want this

2024-03-27 11:32 UTC, jeawhanlee commented on config/wp.config.sample.ts
> +	llcssSingleColon: {
Same here

2024-03-27 13:55 UTC, jeawhanlee requested changes

2024-03-27 13:55 UTC, jeawhanlee commented on src/features/ll-css-bg-image-double-colon.feature
> +        Then I must not see any visual regression 'llcssDoubleColon'
```suggestion
        Then I must not see any visual regression 'doubleColon'
```

2024-03-27 13:55 UTC, jeawhanlee commented on src/features/ll-css-bg-image-single-colon.feature
> +        Then I must not see any visual regression 'llcssSingleColon'
```suggestion
        Then I must not see any visual regression 'singleColon'
```

2024-04-02 08:29 UTC, jeawhanlee approved these changes

2024-04-03 07:47 UTC, Mai-Saad commented
@Miraeld Thanks for the PR. Please find notes below:
1- Two of the backstop-generated reports are empty (probably the ones related to single/double colon templates) => I checked backstop.json here and can't see any entry for the 2 new pages
2- The templates of single/double colon require hover on some elements, so we can either handle hover on test or see if we can update the template itself .. @jeawhanlee what do you think?

2024-04-05 08:04 UTC, Mai-Saad commented
- Updated double colon template to include the markup for :: and : without hover and it's working fine 
- For the hover https://github.com/wp-media/wp-rocket-e2e/issues/65

2024-04-05 08:05 UTC, merged