Closes #59: Deletes or rename `debug.log` file before tests
wp-media/wp-rocket-e2e pull request #60
Opened 2024-03-28 05:03 UTC by Miraeld

# Description

Fixes #59 
## Documentation

### User documentation

It will deletes the `debug.log` before running tests, and once the test process is started, it will rename `debug.log` if it exists to `debug-{previousTestName.log`.

It requires to setup the `ssh` environment within the `wp.config.ts`  to work. 

### Technical documentation

## Type of change
*Delete options that are not relevant.*

- [x] Enhancement (non-breaking change which improves an existing functionality).

## New dependencies

## Risks

# Checklists

## Feature validation

- [x] I validated all the Acceptance Criteria. If possible, provide sreenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.

2024-03-28 09:15 UTC, jeawhanlee commented on src/support/hooks.ts
> +        await rm(debugLogPath);
I believe we should not only remove the debug.log but every scenario debug.log so we don't have unnecessary logs piled up over time.

2024-03-28 09:17 UTC, MathieuLamiot commented on src/support/hooks.ts
> +        await rm(debugLogPath);
Maybe @wp-media/qa-team can help here, if they have a preference?

2024-03-28 09:48 UTC, Miraeld commented on src/support/hooks.ts
> +        await rm(debugLogPath);
Umm, yea that's not a bad idea. 
We could do delete everything that ends by `.log`

2024-03-28 13:32 UTC, hanna-meda commented on src/support/hooks.ts
> +        await rm(debugLogPath);
I agree with removing them from all places.

2024-03-28 13:47 UTC, jeawhanlee submitted a review, later dismissed

2024-04-02 07:55 UTC, jeawhanlee submitted a review, later dismissed

2024-04-02 11:31 UTC, jeawhanlee requested changes

2024-04-02 11:31 UTC, jeawhanlee commented on src/support/steps/general.ts
>  Then('I must not see any error in debug.log', async function (this: ICustomWorld){
I think we should tackle the changes made here in another PR as it covers a sensitive part of the e2e which does more than just checking for the existence of the debug.log but also checking that there are no entries related to wp-rocket in the debug.log

2024-04-02 11:32 UTC, jeawhanlee commented on src/support/steps/general.ts
>  Then('I must not see any error in debug.log', async function (this: ICustomWorld){
@MathieuLamiot Since @Miraeld is not going to available until after the CD Sprint, Should I revert the changes on that module so QA can test that the actual implementation works as expected?

2024-04-02 13:12 UTC, MathieuLamiot commented on src/support/steps/general.ts
>  Then('I must not see any error in debug.log', async function (this: ICustomWorld){
Yes please 🙏 
And can you open a GH issue to track what you removed, so that we can consider adding it back later on?

2024-04-04 13:27 UTC, hanna-meda commented
@Miraeld, @jeawhanlee, me and @Mai-Saad tested this, and here are the conclusions:

- 1st part, `debug.log` deleted before running tests ✓ is happening as expected;
- 2nd part, rename debug.log if it exists to `debug-{previousTestName}.log` x this isn't working, file is not renamed;

We tested by having a page template added to a test, that triggered a PHP fatal error in the debug.log file

`[04-Apr-2024 13:22:02 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function undefined() in /var/www/e2e.rocketlabsqa.ovh/htdocs/wp-content/rocket-test-data/templates/triggerErrorInDebug.php:6
Stack trace:
#0 /var/www/e2e.rocketlabsqa.ovh/htdocs/wp-includes/template-loader.php(106): include()
#1 /var/www/e2e.rocketlabsqa.ovh/htdocs/wp-blog-header.php(19): require_once('...')
#2 /var/www/e2e.rocketlabsqa.ovh/htdocs/index.php(17): require('...')
#3 {main}
  thrown in /var/www/e2e.rocketlabsqa.ovh/htdocs/wp-content/rocket-test-data/templates/triggerErrorInDebug.php on line 6`
but the debug.log file was not suffixed as expected, with the scenario's name.

Expected here would be that we rename the debug.log for every scenario that creates it irrespective of whether the error it’s wpr related or not.

2024-04-04 20:55 UTC, jeawhanlee commented
Thanks @hanna-meda I pushed a fix for this. 
Please note that we will rename the debug.log whether it has WPR related errors in it or not.

2024-04-05 10:40 UTC, Khadreal approved these changes

2024-04-05 12:17 UTC, hanna-meda approved these changes
debug.log entries are deleting before running tests ✓
debug.log file is suffixed by the scenario name during which errors were caught ✓
- if errors contain any of the patterns:
`/plugins/wp-rocket/,
wpr_rucss_used_css,
wpr_rocket_cache,`
scenario(s) will fail 
- if any other error, not wpr related, the scenario will be pass.

2024-04-05 12:22 UTC, jeawhanlee approved these changes

2024-04-05 12:23 UTC, merged