:chore: Add scenario and step for relative lcp image template -- #85
wp-media/wp-rocket-e2e pull request #86
Opened 2024-05-20 13:12 UTC by Khadreal

# Description
Add scenario to test for lcp image with relative url that should have `fetchpriority` attribute

Fixes #85 

## Documentation

### User documentation

*Explain how this code impacts users.*

### Technical documentation

*Explain how this code works. Diagram & drawings are welcomed.*

## Type of change
- [x] Enhancement (non-breaking change which improves an existing functionality).

## New dependencies
*List any new dependencies that are required for this change.*

## Risks
*List possible performance & security issues or risks, and explain how they have been mitigated.*

# Checklists

## Feature validation

- [ ] I validated all the Acceptance Criteria. If possible, provide sreenshots or videos.
- [ ] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I implemented built-in tests to cover the new/changed code.

## Documentation

- [ ] I prepared the user documentation for the feature/enhancement and shared it in the PR or the GitHub issue.
- [ ] The user documentation covers new/changed entry points (endpoints, WP hooks, configuration files, ...).
- [ ] I prepared the technical documentation if needed, and shared it in the PR or the GitHub issue.

## Code style
- [ ] I wrote self-explanatory code about what it does.
- [ ] I wrote comments to explain why it does it.
- [ ] I named variables and functions explicitely.
- [ ] I protected entry points against unexpected inputs.
- [ ] I did not introduce unecessary complexity.
- [ ] I listed the introduced external dependencies explicitely on the PR.
- [ ] I validated the repo-specific guidelines from CONTRIBUTING.md.

## Observability
- [ ] I handled errors when needed.
- [ ] I wrote user-facing messages that are understandable and provide actionable feedbacks.
- [ ] I prepared ways to observe the implemented system (logs, data, etc.).

## Risks
- [ ] I explicitely mentioned performance risks in the PR.
- [ ] I explicitely mentioned security risks in the PR.

2024-05-21 14:19 UTC, jeawhanlee requested changes

2024-05-21 14:19 UTC, jeawhanlee commented on src/features/lcp-beacon-image.feature
> +    #And I go to 'lcp_regular_image_template'
Do we still need this step?

2024-05-21 14:19 UTC, jeawhanlee commented on src/features/lcp-beacon-image.feature
> +    And lcp image in 'lcp_regular_image_template' has fetchpriority
```suggestion
    Then lcp image in 'lcp_regular_image_template' has fetchpriority
```

2024-05-21 14:20 UTC, jeawhanlee commented
After CR is done, We can merge when [this](https://github.com/wp-media/wp-rocket-e2e/pull/77) is merged to trunk

2024-05-26 22:26 UTC, Miraeld approved these changes

2024-05-29 07:04 UTC, jeawhanlee approved these changes

2024-05-29 08:37 UTC, merged